# SPDX-FileCopyrightText: 2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

syntax = "Lua51"
indent_width = 2
indent_type = "Spaces"

[sort_requires]
enabled = true
